//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DocumentShare.Models;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DocumentShareEntities : DbContext
{
    public DocumentShareEntities()
        : base("name=DocumentShareEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Document> Documents { get; set; }
    public DbSet<User> Users { get; set; }
    public DbSet<UserDocument> UserDocuments { get; set; }
}
